services:
  nginx:
    image: nginx:1.25.1-alpine
    hostname: nginx
    container_name: nginx
    volumes: 
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - $PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - $PWD/nginx/certs/:/etc/nginx/conf.d/certs/
    networks:
      - metanet1
      - metanet2
    ports:
      - 8443:443
      - 8080:80
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 64M
        reservations:
          cpus: '0.5'
          memory: 32M
    depends_on:
      metabase:
        condition: service_healthy
  metabase:
    image: metabase/metabase-enterprise:v1.47.0
    container_name: metabase
    hostname: metabase
    volumes: 
      - /dev/urandom:/dev/random:ro
    environment: 
      MB_SITE_URL: https://localhost:8443/
      JAVA_TOOL_OPTIONS: -Xmx1488m -Xms500m
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 3072M
        reservations:
          cpus: '4'
          memory: 1536M
    networks: 
      - metanet1
    healthcheck:
      test: curl --fail -X GET -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 10
  setup:
    image: bash:5.2.15
    container_name: setup
    volumes:
      - $PWD/setup:/tmp
    networks:
      - metanet1
    depends_on:
      metabase:
        condition: service_healthy
    command: sh /tmp/metabase-setup.sh metabase:3000
    cpus: 1
    mem_limit: 128m

networks: 
  metanet1:
    driver: bridge
  metanet2:
    driver: bridge
